apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: okd-fcos

resources:
  - ../../buildconfigs
  - ../../pipelines

patches:
  - patch: |-
      - op: add
        path: /spec/strategy/dockerStrategy/buildArgs/-
        value:
          name: "TAGS"
          value: "fcos"
    target:
      labelSelector: "change-build-arg-tags==true"
      kind: BuildConfig
  - patch: |-
      - op: add
        path: "/spec/tags/-"
        value:
          name: fedora-coreos
          from:
            kind: DockerImage
            name: quay.io/fedora/fedora-coreos:next-devel
          referencePolicy:
            type: Source
    target:
      kind: ImageStream
      name: tools
  - patch: |-
      - op: add
        path: "/spec/tags/-"
        value:
          name: machine-os-content
          from:
            kind: ImageStreamTag
            name: release:fedora-coreos
    target:
      kind: ImageStream
      name: release
  - patch: |-
      - op: add
        path: "/spec/tasks/4/params/1/value/-"
        value:
          fedora-coreos
    target:
      kind: Pipeline
      name: build-from-scratch

