---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tools
spec:
  lookupPolicy:
    local: true
  tags:
    - name: centos9
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/centos/centos:stream9'
      referencePolicy:
        type: Local
    - name: fedora36
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/fedora/fedora:36'
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: installer-artifacts
