apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ovn-kubernetes
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ovn-kubernetes'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      # Dockerfile.rhel9 is suitable for 4.13 only
      dockerfilePath: Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:ovn-kubernetes-base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:ovn-kubernetes'
