kind: List
apiVersion: v1
items:
  # Needed to allow the memoization feature work with configmaps
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: edit-config-map
      namespace: argo-workflows
    rules:
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - create
          - update
          - patch
          - delete
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: argo-edit-config-map
      namespace: argo-workflows
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: edit-config-map
    subjects:
      - kind: ServiceAccount
        name: argo
        namespace: argo-workflows